[package]
name = "hit-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored_json = "5.0.0"
convert_case = "0.6.0"
edit = "0.1.5"
getopts = "0.2.21"
regex = "1.10.4"
reqwest = {version="0.12.3", features=["json"]}
serde_json = "1.0"
tokio = {version = "1.37.0", features = ["full"]}
